Repository chingu-voyage6/Bears-Team-07, pull requests merged in 2018-07, with the labels that each got.

#29 add puffs endpoint
  server/server.js
  server/src/controllers/auth/auth.js
  server/src/controllers/puffs/puff.js
  server/src/controllers/puffs/router.js
  server/src/controllers/users/user.js
  server/src/models/puff.js
  server/src/models/user.js
  server/src/routes.js
  server/src/schemas/userSchema.js
  server/src/services/jwt.js
Labels: in progress, review

#33 Feature/puffs images
  server/.env.config
  server/.gitignore
  server/backpack.config.js
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/controllers/auth/auth.js
  server/src/controllers/puffs/puff.js
  server/src/controllers/puffs/router.js
  server/src/controllers/users/router.js
  server/src/controllers/users/user.js
  server/src/models/puff.js
  server/src/models/user.js
  server/src/schemas/index.js
  server/src/schemas/userSchema.js
  server/yarn.lock
Labels: enhancement, in progress

#40 Feature/image upload
  client/.env
  client/src/App.vue
  client/src/components/Feed.vue
  client/src/services/LoginService.js
  client/src/services/PuffService.js
  client/src/services/createPuffService.js
  client/src/services/readPuffsService.js
  client/src/views/Home.vue
  client/src/views/Register.vue
  client/src/views/Welcome.vue
Labels: review

#42 Feature/logout
  client/src/components/WelcomeHeader.vue
Labels: review

#45 remove refs after deleting a puff
  server/src/controllers/puffs/puff.js
  server/src/controllers/users/user.js
  server/src/models/puff.js
  server/src/models/user.js
Labels: bug, review
