Repository chingu-voyage6/Bears-Team-07, pull requests merged in 2018-08, with the labels that each got.

#46 Feature/edit delete puff
  client/src/App.vue
  client/src/components/Feed.vue
  client/src/components/WelcomeHeader.vue
  client/src/services/PuffService.js
  client/src/views/Home.vue
  client/src/views/Login.vue
  client/src/views/Register.vue
Labels: review

#48 Enhancements/favorites
  client/src/components/Feed.vue
  client/src/views/Home.vue
  server/src/controllers/puffs/puff.js
  server/src/controllers/puffs/router.js
  server/src/models/puff.js
  server/src/schemas/index.js
Labels: enhancement

#49 add image removal to the PUT/update method
  server/src/controllers/puffs/puff.js
  server/src/schemas/index.js
Labels: enhancement

#50 Feature/remove attachment frontend
  README.md
  client/src/views/Home.vue
Labels: review

#53 Feature/user profile page
  client/public/img/avatar1.png
  client/public/img/avatar2.png
  client/src/App.vue
  client/src/components/Feed.vue
  client/src/components/WelcomeHeader.vue
  client/src/router.js
  client/src/services/UserService.js
  client/src/store/store.js
  client/src/views/Home.vue
  client/src/views/UserProfile.vue
  server/src/controllers/users/user.js
Labels: enhancement, in progress

#54 added css and form row for puff title and content
  client/src/views/Home.vue
Labels: enhancement
